# render.yaml
services:
  - type: web
    name: voice-widget
    runtime: node
    plan: free
    rootDir: app
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production