# render.yaml
services:
  - type: web
    name: voice-widget
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here
      - key: ASSISTANT_ID
        value: your_assistant_id_here
      - key: PORT
        value: 10000